FROM node:22-slim

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends openssl curl && \
    rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

RUN yarn install

COPY prisma ./prisma/

RUN npx prisma generate

EXPOSE 3344
EXPOSE 5555

CMD ["yarn", "dev"]
