services:
  db:
    container_name: salvacao_db_dev
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    # networks:
    #   - salvacao_network_dev
    environment:
      POSTGRES_DB: cachorrinhodb
      POSTGRES_USER: salvacao 
      POSTGRES_PASSWORD: salvacao123
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salvacao -d cachorrinhodb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
  
  # Backend API (development configuration)
  # api:
  #   container_name: salvacao_api_dev
  #   build: 
  #     context: ./cachorrinho-express
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./cachorrinho-express:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://salvacao:salvacao123@db:5432/cachorrinhodb?connect_timeout=30
  #     NODE_ENV: development
  #     PORT: 3344
  #   # networks:
  #   #   - salvacao_network_dev
  #   ports:
  #     - "3344:3344"
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3344/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 15s
    
  # dashboard:
  #   container_name: salvacao_dashboard_dev
  #   build:
  #     context: ./admin-dashboard
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./admin-dashboard:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     NODE_ENV: development
  #   # networks:
  #   #   - salvacao_network_dev
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   restart: always
  
  # nginx:
  #   container_name: salvacao_nginx_dev
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - dashboard
  #     - api
  #   networks:
  #     - salvacao_network_dev
  #   restart: always

volumes:
  postgres_data_dev:

# networks:
#   salvacao_network_dev:
#     driver: bridge
