export enum TipoDocumento {
  CPF = "CPF",
  RG = "RG",
}

export enum TipoUsuario {
  ADMIN = "ADMIN",
  USER = "USER",
}

export enum SexoAnimal {
  MACHO = "MACHO",
  FEMEA = "FEMEA",
  DESCONHECIDO = "DESCONHECIDO",
}

export enum PorteAnimal {
  MINI = "MINI",
  PEQUENO = "PEQUENO",
  MEDIO = "MEDIO",
  GRANDE = "GRANDE",
  GIGANTE = "GIGANTE",
}

export enum StatusAnimal {
  RESGATADO = "RESGATADO",
  EM_TRATAMENTO = "EM_TRATAMENTO",
  DISPONIVEL_ADOCAO = "DISPONIVEL_ADOCAO",
  EM_LAR_TEMPORARIO = "EM_LAR_TEMPORARIO",
  ADOTADO = "ADOTADO",
  FALECIDO = "FALECIDO",
  EM_OBSERVACAO = "EM_OBSERVACAO",
  PERDIDO = "PERDIDO",
  DEVOLVIDO = "DEVOLVIDO",
}

export enum StatusAdocao {
  SOLICITADA = "SOLICITADA",
  EM_ANALISE = "EM_ANALISE",
  APROVADA = "APROVADA",
  REJEITADA = "REJEITADA",
  CANCELADA = "CANCELADA",
  CONCLUIDA = "CONCLUIDA",
  ACOMPANHAMENTO = "ACOMPANHAMENTO",
  DEVOLVIDO = "DEVOLVIDO",
}

export enum TipoMoradia {
  CASA_COM_QUINTAL_TOTALMENTE_MURADO = "CASA_COM_QUINTAL_TOTALMENTE_MURADO",
  CASA_COM_QUINTAL_PARCIALMENTE_MURADO = "CASA_COM_QUINTAL_PARCIALMENTE_MURADO",
  CASA_SEM_QUINTAL = "CASA_SEM_QUINTAL",
  APARTAMENTO_COM_TELA_PROTECAO = "APARTAMENTO_COM_TELA_PROTECAO",
  APARTAMENTO_SEM_TELA_PROTECAO = "APARTAMENTO_SEM_TELA_PROTECAO",
  CHACARA = "CHACARA",
  SITIO = "SITIO",
  FAZENDA = "FAZENDA",
  COMUNIDADE = "COMUNIDADE",
  OUTRO = "OUTRO",
}

export enum StatusAgendamento {
  AGENDADO = "AGENDADO",
  CONFIRMADO = "CONFIRMADO",
  REALIZADO = "REALIZADO",
  CANCELADO_PELO_USUARIO = "CANCELADO_PELO_USUARIO",
  CANCELADO_PELA_ONG = "CANCELADO_PELA_ONG",
  REAGENDADO = "REAGENDADO",
  NAO_COMPARECEU = "NAO_COMPARECEU",
  EM_ANDAMENTO = "EM_ANDAMENTO",
}

export enum TipoCompromisso {
  CONSULTA_VETERINARIA_ROTINA = "CONSULTA_VETERINARIA_ROTINA",
  CONSULTA_VETERINARIA_EMERGENCIA = "CONSULTA_VETERINARIA_EMERGENCIA",
  VACINACAO = "VACINACAO",
  VERMIFUGACAO = "VERMIFUGACAO",
  CIRURGIA_CASTRACAO = "CIRURGIA_CASTRACAO",
  CIRURGIA_GERAL = "CIRURGIA_GERAL",
  EXAME_LABORATORIAL = "EXAME_LABORATORIAL",
  EXAME_IMAGEM = "EXAME_IMAGEM",
  BANHO_E_TOSA = "BANHO_E_TOSA",
  ENTREVISTA_ADOCAO_ADOTANTE = "ENTREVISTA_ADOCAO_ADOTANTE",
  VISITA_PRE_ADOCAO_MORADIA = "VISITA_PRE_ADOCAO_MORADIA",
  VISITA_ACOMPANHAMENTO_POS_ADOCAO = "VISITA_ACOMPANHAMENTO_POS_ADOCAO",
  TRANSPORTE_ANIMAL = "TRANSPORTE_ANIMAL",
  EVENTO_FEIRA_ADOCAO = "EVENTO_FEIRA_ADOCAO",
  TREINAMENTO_COMPORTAMENTAL = "TREINAMENTO_COMPORTAMENTAL",
  SESSAO_FISIOTERAPIA = "SESSAO_FISIOTERAPIA",
  OUTRO = "OUTRO",
}

export enum TipoDoacao {
  MONETARIA_DINHEIRO = "MONETARIA_DINHEIRO",
  MONETARIA_PIX = "MONETARIA_PIX",
  MONETARIA_CARTAO_CREDITO = "MONETARIA_CARTAO_CREDITO",
  MONETARIA_BOLETO = "MONETARIA_BOLETO",
  PRODUTO_ALIMENTO = "PRODUTO_ALIMENTO",
  PRODUTO_MEDICAMENTO = "PRODUTO_MEDICAMENTO",
  PRODUTO_HIGIENE_LIMPEZA = "PRODUTO_HIGIENE_LIMPEZA",
  PRODUTO_ACESSORIO_BRINQUEDO = "PRODUTO_ACESSORIO_BRINQUEDO",
  PRODUTO_MATERIAL_CONSTRUCAO_REFORMA = "PRODUTO_MATERIAL_CONSTRUCAO_REFORMA",
  SERVICO_VETERINARIO = "SERVICO_VETERINARIO",
  SERVICO_TRANSPORTE = "SERVICO_TRANSPORTE",
  SERVICO_LAR_TEMPORARIO = "SERVICO_LAR_TEMPORARIO",
  SERVICO_TREINAMENTO = "SERVICO_TREINAMENTO",
  SERVICO_DIVULGACAO_MARKETING = "SERVICO_DIVULGACAO_MARKETING",
  SERVICO_FOTOGRAFIA_VIDEO = "SERVICO_FOTOGRAFIA_VIDEO",
  OUTRO = "OUTRO",
}

export enum TipoInteracao {
  TELEFONEMA_REALIZADO = "TELEFONEMA_REALIZADO",
  TELEFONEMA_RECEBIDO = "TELEFONEMA_RECEBIDO",
  MENSAGEM_TEXTO_WHATSAPP_ENVIADA = "MENSAGEM_TEXTO_WHATSAPP_ENVIADA",
  MENSAGEM_TEXTO_WHATSAPP_RECEBIDA = "MENSAGEM_TEXTO_WHATSAPP_RECEBIDA",
  EMAIL_ENVIADO = "EMAIL_ENVIADO",
  EMAIL_RECEBIDO = "EMAIL_RECEBIDO",
  VISITA_PRESENCIAL_REALIZADA_NA_ONG = "VISITA_PRESENCIAL_REALIZADA_NA_ONG",
  VISITA_PRESENCIAL_REALIZADA_EXTERNA = "VISITA_PRESENCIAL_REALIZADA_EXTERNA",
  VIDEO_CHAMADA_REALIZADA = "VIDEO_CHAMADA_REALIZADA",
  CONTATO_REDES_SOCIAIS = "CONTATO_REDES_SOCIAIS",
  RELATORIO_ESCRITO = "RELATORIO_ESCRITO",
  OUTRO = "OUTRO",
}

export enum ViaAdministracaoMedicamento {
  ORAL_COMPRIMIDO = "ORAL_COMPRIMIDO",
  ORAL_LIQUIDO = "ORAL_LIQUIDO",
  ORAL_PASTA = "ORAL_PASTA",
  INTRAMUSCULAR = "INTRAMUSCULAR",
  SUBCUTANEA = "SUBCUTANEA",
  INTRAVENOSA = "INTRAVENOSA",
  TOPICA_PELE = "TOPICA_PELE",
  TOPICA_OCULAR = "TOPICA_OCULAR",
  TOPICA_AURICULAR = "TOPICA_AURICULAR",
  INALATORIA = "INALATORIA",
  RETAL = "RETAL",
  OUTRA = "OUTRA",
}
