export enum TipoMoradia {
  CASA_COM_QUINTAL_TOTALMENTE_MURADO = "CASA_COM_QUINTAL_TOTALMENTE_MURADO",
  CASA_COM_QUINTAL_PARCIALMENTE_MURADO = "CASA_COM_QUINTAL_PARCIALMENTE_MURADO",
  CASA_SEM_QUINTAL = "CASA_SEM_QUINTAL",
  APARTAMENTO_COM_TELA_PROTECAO = "APARTAMENTO_COM_TELA_PROTECAO",
  APARTAMENTO_SEM_TELA_PROTECAO = "APARTAMENTO_SEM_TELA_PROTECAO",
  CHACARA = "CHACARA",
  SITIO = "SITIO",
  FAZENDA = "FAZENDA",
  COMUNIDADE = "COMUNIDADE",
  OUTRO = "OUTRO",
} 